# Staging Environment Inventory

[k8s_master]
stage-master-01 ansible_host=10.10.10.11 ansible_user=deploy

[k8s_worker]
stage-worker-01 ansible_host=10.10.10.12 ansible_user=deploy
stage-worker-02 ansible_host=10.10.10.13 ansible_user=deploy

[k8s_cluster:children]
k8s_master
k8s_worker

[gpu_nodes]
stage-worker-02 ansible_host=10.10.10.13 ansible_user=deploy

[all:vars]
ansible_python_interpreter=/usr/bin/python3
env=stage
