# Production Environment Inventory

[k8s_master]
prod-master-01 ansible_host=10.20.20.11 ansible_user=deploy
prod-master-02 ansible_host=10.20.20.12 ansible_user=deploy

[k8s_worker]
prod-worker-01 ansible_host=10.20.20.21 ansible_user=deploy
prod-worker-02 ansible_host=10.20.20.22 ansible_user=deploy
prod-worker-03 ansible_host=10.20.20.23 ansible_user=deploy

[k8s_cluster:children]
k8s_master
k8s_worker

[gpu_nodes]
prod-worker-02 ansible_host=10.20.20.22 ansible_user=deploy
prod-worker-03 ansible_host=10.20.20.23 ansible_user=deploy

[all:vars]
ansible_python_interpreter=/usr/bin/python3
env=prod
