# Dev Environment Inventory

[k8s_master]
dev-master-01 ansible_host=192.168.56.11 ansible_user=deploy

[k8s_worker]
dev-worker-01 ansible_host=192.168.56.12 ansible_user=deploy
dev-worker-02 ansible_host=192.168.56.13 ansible_user=deploy

[k8s_cluster:children]
k8s_master
k8s_worker

# Group for GPU Nodes (for custom GPU setups/simulations)
[gpu_nodes]
dev-worker-02 ansible_host=192.168.56.13 ansible_user=deploy

[all:vars]
ansible_python_interpreter=/usr/bin/python3
env=dev
